# Generated by Django 5.2.15 on 2026-06-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('clinic_type', models.CharField(choices=[('GP', 'GP Practice'), ('Physiotherapy', 'Physiotherapy'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Orthopaedics', 'Orthopaedics'), ('Psychiatry', 'Psychiatry')], max_length=50)),
                ('address', models.TextField(blank=True)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(choices=[('GP', 'General Practitioner'), ('Physiotherapy', 'Physiotherapy'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Orthopaedics', 'Orthopaedics'), ('Psychiatry', 'Psychiatry')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=20, unique=True)),
                ('appointment_type', models.CharField(choices=[('New Patient', 'New Patient'), ('Follow-up', 'Follow-up'), ('Emergency', 'Emergency'), ('Routine', 'Routine')], default='Follow-up', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('appointment_date', models.DateField()),
                ('appointment_hour', models.IntegerField(default=9)),
                ('consultation_fee_gbp', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-Show', 'No-Show')], default='Scheduled', max_length=20)),
                ('no_show', models.BooleanField(default=False)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_peak_hour', models.BooleanField(default=False)),
                ('days_in_advance', models.IntegerField(default=0)),
                ('sms_reminder_sent', models.BooleanField(default=False)),
                ('reminder_hours_before', models.IntegerField(default=24)),
                ('reminder_response', models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('No Response', 'No Response'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('number_of_reminders_sent', models.IntegerField(default=0)),
                ('estimated_revenue_loss_gbp', models.FloatField(default=0.0)),
                ('staff_idle_cost_gbp', models.FloatField(default=0.0)),
                ('slot_rebooked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.doctor')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_hour'],
            },
        ),
    ]
