# Generated by Django 5.2.15 on 2026-06-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('postcode_area', models.CharField(max_length=10)),
                ('distance_to_clinic_km', models.FloatField(default=0.0)),
                ('has_chronic_condition', models.BooleanField(default=False)),
                ('total_appointments', models.IntegerField(default=0)),
                ('previous_noshow_count', models.IntegerField(default=0)),
                ('noshow_rate', models.FloatField(default=0.0)),
                ('days_since_last_visit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
